### PR TITLE
doc: update project links

### LINKED ISSUE #393: [Adoption] Update links for new repo
The repo has moved from:
https://github.com/felixrieseberg/ember-electron/
To:
https://github.com/adopted-ember-addons/ember-electron/

Currently a few places are still linking to the old repo. This needs to be updated.

### PR DESCRIPTION
**Pull request by jacobq**
felixrieseberg -> adopted-ember-addons (fixes #393)

### CODE REVIEW

**Comment by Alonski** [comment]
Awesome! Could you also update authors in both the package.json and Readme please?

**Comment by jacobq** [comment]
> Awesome! Could you also update authors in both the package.json and Readme please?

Has the author changed? What do you want it to say?

IMHO the easiest, meaningful visualization of contributor activity is https://github.com/adopted-ember-addons/ember-electron/graphs/contributors which we already have linked

**Comment by Alonski** [comment]
I guess the fact that Felix is still an author. So people might want his help instead of the current maintainers.
Maybe remove anyone not currently maintaining and add a new section for Alumni maintainers?

If you disagree feel free to merge.

**Comment by jacobq** [comment]
> Maybe remove anyone not currently maintaining and add a new section for Alumni maintainers?
> If you disagree feel free to merge.

I suppose that makes sense. I would be in favor of removing all authors/contributors from `package.json` (to match ember.js source) and just using the bottom of the README for that.

**Comment by Alonski** [comment]
@jacobq The issue with not having any authors/contributors in `package.json` is that they won't show up on NPM/Ember Observer etc
Which I think we do actually want.

**Comment by Alonski** [comment]
@jacobq Do you feel that this can be merged?

**Comment by jacobq** [comment]
> @jacobq Do you feel that this can be merged?

Sure, I just never got back to considering what to do about "authors" metadata. We can always go back and update/fix that later though.

**Pull request merged**
