### PR TITLE
Bump various deps, drop node 8 support

### PR DESCRIPTION
**Pull request by rwwagner90**
This bumps a lot of deps, many of which no longer support node 8, so I also changed our node engines to 10.x+.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@bendemboski @jacobq any ideas why the build is failing? I'm not familiar with the `electron make` tests.

**Comment by bendemboski** [comment]
It basically just creates a new Ember project, installs `ember-electron` and then runs through the basic commands. So in theory you should be able to reproduce this by

```sh
$ ember new ee-test
$ cd ee-test
$ ember install ember-electron@git+ssh://... # git URL pointing to the failing build
$ ember electron:make
```

**Comment by rwwagner90** [comment]
@bendemboski it looks like the problem is `Error: Could not find any make targets configured for the "linux" platform`. `yarn test` locally runs fine for me.

**Comment by bendemboski** [comment]
Are you running locally on linux?

**Comment by rwwagner90** [comment]
@bendemboski no, I am on MacOS.

**Comment by rwwagner90** [comment]
Closing this and going to try updating deps in smaller chunks tomorrow.

**Pull request closed without merging**
